name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: |
          go test -coverprofile coverage.out -covermode atomic ./...
        shell: bash
